using BeNurse.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace BeNurse.Infrastructure.Data;

public static class DbInitializer
{
    public static async Task Initialize(BeNurseDbContext context)
    {
        await context.Database.EnsureCreatedAsync();

        await context.Database.ExecuteSqlRawAsync(@"
            ALTER TABLE ""ChatMessages""
            ADD COLUMN IF NOT EXISTS ""IsNurseReply"" boolean NOT NULL DEFAULT false
        ");

        // EnsureCreated no anade tablas a una base de datos que ya existe, asi que
        // las nuevas se crean a mano, como ya se hacia con la columna de arriba.
        await context.Database.ExecuteSqlRawAsync(@"
            CREATE TABLE IF NOT EXISTS ""ContentBlocks"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""Key"" character varying(200) NOT NULL,
                ""Type"" character varying(20) NOT NULL,
                ""Value"" text NOT NULL,
                ""UpdatedAt"" timestamp with time zone NOT NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ""IX_ContentBlocks_Key"" ON ""ContentBlocks"" (""Key"");

            CREATE TABLE IF NOT EXISTS ""ContentGroups"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""Key"" character varying(200) NOT NULL,
                ""UpdatedAt"" timestamp with time zone NOT NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ""IX_ContentGroups_Key"" ON ""ContentGroups"" (""Key"");

            CREATE TABLE IF NOT EXISTS ""ContentCards"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""ContentGroupId"" integer NOT NULL REFERENCES ""ContentGroups""(""Id"") ON DELETE CASCADE,
                ""Position"" integer NOT NULL,
                ""Title"" text NOT NULL,
                ""Body"" text NOT NULL,
                ""ItemsJson"" text NOT NULL,
                ""Image"" text NOT NULL,
                ""Badge"" text NOT NULL
            );
            CREATE INDEX IF NOT EXISTS ""IX_ContentCards_ContentGroupId_Position""
                ON ""ContentCards"" (""ContentGroupId"", ""Position"");

            -- El valor por defecto va vacio a proposito: ExecuteSqlRaw interpreta
            -- las llaves como marcadores de formato y un JSON vacio aqui reventaria.
            ALTER TABLE ""ContentCards""
                ADD COLUMN IF NOT EXISTS ""FieldsJson"" text NOT NULL DEFAULT '';

            CREATE TABLE IF NOT EXISTS ""MediaAssets"" (
                ""Id"" uuid PRIMARY KEY,
                ""FileName"" character varying(300) NOT NULL,
                ""ContentType"" character varying(100) NOT NULL,
                ""Data"" bytea NOT NULL,
                ""CreatedAt"" timestamp with time zone NOT NULL
            );
        ");

        // El contenido de Content es HTML: la vista de detalle lo pinta con [innerHTML]
        // (Angular lo sanea) para poder usar titulares, listas y enlaces.
        var seed = new List<Article>
        {
            new()
            {
                Title = "Definicion de Infeccion de Transmision Sexual",
                Slug = "definicion-its",
                Category = "informate",
                SubCategory = "definicion",
                AuthorName = "Equipo BE nurse",
                Content = "<p>Las Infecciones de Transmision Sexual (ITS) se caracterizan por contagiarse a traves del contacto sexual. En la mayoria de los casos las manifestaciones clinicas comprometen la zona genital y las mucosas, dando lugar a complicaciones medicas. Ademas, muchas de estas infecciones pueden no ser sintomaticas, por lo que se dificulta su tratamiento y diagnostico.</p>",
                Excerpt = "Que son las ITS y por que es importante conocerlas.",
                PublishedAt = new DateTime(2026, 2, 1, 0, 0, 0, DateTimeKind.Utc),
                IsPublished = true,
                ImageUrl = ""
            },
            new()
            {
                Title = "VIH: que es y como se transmite",
                Slug = "vih-que-es",
                Category = "informate",
                SubCategory = "its-comunes",
                AuthorName = "Ana Morales",
                Content = "<p>El Virus de Inmunodeficiencia Humana (VIH) ataca el sistema inmunitario del cuerpo, concretamente los linfocitos T CD4. Sin tratamiento, puede progresar a SIDA. Hoy en dia, con tratamiento antirretroviral, las personas con VIH pueden llevar una vida larga y saludable.</p>",
                Excerpt = "Todo lo que necesitas saber sobre el Virus de Inmunodeficiencia Humana.",
                PublishedAt = new DateTime(2026, 2, 5, 0, 0, 0, DateTimeKind.Utc),
                IsPublished = true,
                ImageUrl = ""
            },
            new()
            {
                Title = "VPH: Virus del Papiloma Humano",
                Slug = "vph-virus-papiloma",
                Category = "informate",
                SubCategory = "its-comunes",
                AuthorName = "Ana Morales",
                Content = "<p>El Virus del Papiloma Humano (VPH) es la infeccion de transmision sexual mas frecuente en el mundo. Existen mas de 100 tipos diferentes. Algunos pueden causar verrugas genitales y otros estan relacionados con el desarrollo de cancer de cuello uterino, anal, orofaringeo y de pene.</p>",
                Excerpt = "El VPH es la ITS mas frecuente en el mundo. Te explicamos todo.",
                PublishedAt = new DateTime(2026, 2, 6, 0, 0, 0, DateTimeKind.Utc),
                IsPublished = true,
                ImageUrl = ""
            },
            new()
            {
                Title = "Clamidia: la ITS silenciosa",
                Slug = "clamidia",
                Category = "informate",
                SubCategory = "its-comunes",
                AuthorName = "Javier Ruiz",
                Content = "<p>La clamidia es causada por la bacteria Chlamydia trachomatis. Es una de las ITS mas comunes y la mayoria de las personas infectadas no presentan sintomas, de ahi su apodo de 'infeccion silenciosa'. Si no se trata, puede causar complicaciones graves como infertilidad.</p>",
                Excerpt = "La clamidia suele ser asintomatica. Por eso es tan importante hacerse pruebas.",
                PublishedAt = new DateTime(2026, 2, 7, 0, 0, 0, DateTimeKind.Utc),
                IsPublished = true,
                ImageUrl = ""
            },
            new()
            {
                Title = "Gonorrea",
                Slug = "gonorrea",
                Category = "informate",
                SubCategory = "its-comunes",
                AuthorName = "Lucia Garcia",
                Content = "<p>La gonorrea es causada por la bacteria Neisseria gonorrhoeae. Puede infectar los genitales, el recto y la garganta. Es tratable con antibioticos, aunque las resistencias a los mismos son un problema creciente de salud publica a nivel mundial.</p>",
                Excerpt = "Causada por la bacteria Neisseria gonorrhoeae. Tratable pero con resistencias crecientes.",
                PublishedAt = new DateTime(2026, 2, 8, 0, 0, 0, DateTimeKind.Utc),
                IsPublished = true,
                ImageUrl = ""
            },
            new()
            {
                Title = "Sifilis",
                Slug = "sifilis",
                Category = "informate",
                SubCategory = "its-comunes",
                AuthorName = "Miguel Torres",
                Content = "<p>La sifilis es una ITS causada por la bacteria Treponema pallidum. Progresa en fases: primaria (chancro), secundaria (erupcion), latente y terciaria. Si se detecta a tiempo, es completamente curable con penicilina.</p>",
                Excerpt = "La sifilis tiene fases distintas. Conocer sus estadios es clave para el tratamiento.",
                PublishedAt = new DateTime(2026, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                IsPublished = true,
                ImageUrl = ""
            },
            new()
            {
                Title = "Por qué el porno distorsiona las expectativas",
                Slug = "porno-distorsiona-expectativas",
                Category = "realidades",
                SubCategory = "porno-sexualidad",
                AuthorName = "Lucía García",
                Content = """
                    <h2>Pornografía y sexualidad: mirar con pensamiento crítico</h2>
                    <p>La pornografía forma parte del entorno digital de muchas personas jóvenes. No hablar de ella no hace que desaparezca. Al contrario: cuando falta educación sexual clara, cercana y adaptada a la edad, la pornografía puede ocupar ese espacio y convertirse en una fuente de aprendizaje poco realista.</p>
                    <p>Según Save the Children, casi 7 de cada 10 adolescentes consumen pornografía y el primer acceso se produce alrededor de los 12 años. Además, para el 30% de adolescentes que ven pornografía, estos contenidos son su única fuente de información sobre sexualidad.</p>

                    <h2>1. El porno no está diseñado para educar</h2>
                    <p>La pornografía puede mostrar prácticas sexuales, pero no suele enseñar los elementos esenciales de una sexualidad saludable:</p>
                    <ul>
                      <li>Comunicación.</li>
                      <li>Consentimiento.</li>
                      <li>Respeto.</li>
                      <li>Límites.</li>
                      <li>Diversidad corporal.</li>
                      <li>Prevención.</li>
                      <li>Cuidado emocional.</li>
                      <li>Responsabilidad afectiva.</li>
                    </ul>
                    <p>Por eso, el problema no es hablar de sexualidad. El problema es aprender sexualidad desde contenidos que no explican cómo se construye una relación segura, libre y respetuosa.</p>
                    <blockquote>El porno puede mostrar sexo, pero no enseña necesariamente a cuidar, respetar ni comunicar.</blockquote>

                    <h2>2. Qué expectativas puede distorsionar</h2>
                    <h3>Cuerpo</h3>
                    <p>Puede generar comparación, presión estética y expectativas irreales sobre cómo debería ser un cuerpo o cómo debería responder sexualmente.</p>
                    <h3>Deseo</h3>
                    <p>Puede transmitir la idea de que todas las personas desean lo mismo, siempre están disponibles o deben aceptar determinadas prácticas.</p>
                    <h3>Consentimiento</h3>
                    <p>Muchas escenas no muestran comunicación previa, negociación de límites ni un consentimiento claro. En la vida real, el consentimiento debe ser libre, explícito, reversible y sin presión.</p>
                    <h3>Relaciones</h3>
                    <p>Puede normalizar desigualdad, cosificación, dominación o prácticas sin afecto, cuidado ni respeto.</p>
                    <h3>Protección</h3>
                    <p>En muchos contenidos no aparece el uso de métodos de protección, lo que puede banalizar prácticas que en la vida real requieren prevención y responsabilidad.</p>

                    <h2>3. Porno, ITS y conductas de riesgo</h2>
                    <p>Aquí hay que ser precisas: no podemos decir que «la pornografía causa ITS» de forma directa. Lo correcto es decir que puede influir en las expectativas, en la percepción del riesgo y en la normalización de ciertas prácticas, especialmente cuando no existe una educación sexual suficiente.</p>
                    <p>Save the Children recoge que más de la mitad de adolescentes que ven pornografía se inspiran en ella para sus propias experiencias. Por eso, la prevención no puede limitarse a hablar de preservativos: también debe abordar los modelos sexuales que influyen en la toma de decisiones.</p>
                    <blockquote>La prevención empieza antes de la práctica sexual: empieza en cómo aprendemos a mirar el cuerpo, el deseo, los límites y el consentimiento.</blockquote>

                    <h2>4. Cómo iniciar el diálogo</h2>
                    <p>Hablar de pornografía no debe hacerse desde la culpa ni desde la vergüenza. Debe hacerse desde el pensamiento crítico.</p>
                    <h3>Reflexionar sobre la primera vez que se vio pornografía</h3>
                    <ul>
                      <li>¿Cómo llegó ese contenido?</li>
                      <li>¿Fue buscado o apareció sin esperarlo?</li>
                      <li>¿Qué emociones generó: curiosidad, incomodidad, vergüenza, presión?</li>
                      <li>¿Aparecía violencia, agresión o ausencia de consentimiento?</li>
                    </ul>
                    <h3>Reflexionar sobre el consumo actual</h3>
                    <ul>
                      <li>¿Por qué se consume pornografía?</li>
                      <li>¿Se diferencia claramente ficción y realidad?</li>
                      <li>¿Se considera que se ve demasiada pornografía?</li>
                      <li>¿Se están normalizando prácticas que en la vida real necesitarían comunicación, respeto y consentimiento?</li>
                    </ul>
                    <h3>Reflexionar sobre cómo afecta a la vida</h3>
                    <ul>
                      <li>¿Influye en las expectativas sobre el cuerpo?</li>
                      <li>¿Influye en las relaciones personales?</li>
                      <li>¿Genera presión, comparación, culpa o vergüenza?</li>
                      <li>¿Ayuda a vivir una sexualidad más sana o crea confusión?</li>
                    </ul>

                    <h2>5. Estrategias educativas</h2>
                    <p>La respuesta no debe basarse en el miedo ni en la prohibición. La estrategia más útil es educativa:</p>
                    <ul>
                      <li>Reconocer que la pornografía existe.</li>
                      <li>Abrir espacios de diálogo sin juicio.</li>
                      <li>Diferenciar ficción y realidad.</li>
                      <li>Trabajar con consentimiento, respeto y límites.</li>
                      <li>Promover pensamiento crítico.</li>
                      <li>Ofrecer recursos fiables.</li>
                      <li>Implicar a familias, profesionales y comunidad educativa.</li>
                    </ul>
                    <p>La UNESCO defiende una educación integral en sexualidad basada en evidencia, derechos humanos, igualdad de género y aprendizaje progresivo sobre sexo y relaciones de forma positiva y adaptada a la edad.</p>

                    <h2>6. Recursos para seguir aprendiendo</h2>
                    <h3>Universidad de La Laguna / VIOSEX</h3>
                    <p>El grupo VIOSEX de la Universidad de La Laguna trabaja en investigación vinculada a violencia sexual. Además, la ULL recoge la Guía sobre pornografía ANDREA, dirigida a profesionales y mediadores juveniles, como herramienta para sensibilizar, prevenir conductas nocivas y fomentar pensamiento crítico sobre el consumo de pornografía.</p>
                    <ul>
                      <li><a href="https://www.ull.es/portal/noticias/2025/ull-coordina-guia-sensibilizacion-jovenes-pornografia/" target="_blank" rel="noopener noreferrer">Guía ANDREA sobre pornografía para profesionales y mediadores juveniles (ULL)</a></li>
                    </ul>
                    <h3>Save the Children</h3>
                    <ul>
                      <li><a href="https://www.savethechildren.es/informe-desinformacion-sexual-pornografia-y-adolescencia" target="_blank" rel="noopener noreferrer">(Des)información sexual: pornografía y adolescencia</a></li>
                    </ul>
                    <h3>Otros recursos educativos</h3>
                    <ul>
                      <li>El porno no mola.</li>
                      <li>Sí es sí, no es no.</li>
                      <li>Habla con ellos de sexualidad.</li>
                      <li>Guías para familias, docentes y mediadores juveniles.</li>
                    </ul>
                    <p>Estos materiales ayudan a abrir conversaciones sin culpabilizar y a trabajar consentimiento, límites, deseo, presión social y relaciones sanas.</p>

                    <h2>7. Enfoque BE NURSE</h2>
                    <p>Desde BE NURSE abordamos la pornografía sin juicio, sin tabúes y sin culpabilizar. Nuestro objetivo es acompañar a la juventud para diferenciar ficción y realidad, reconocer modelos dañinos, cuestionar estereotipos y construir relaciones afectivo-sexuales basadas en respeto, comunicación, consentimiento y cuidado.</p>
                    <blockquote>El porno no puede ser la escuela de la sexualidad. La educación sexual sí puede enseñar a cuidar, respetar, comunicar y decidir con libertad.</blockquote>
                    """,
                Excerpt = "La pornografía forma parte del entorno digital de muchas personas jóvenes, pero no está diseñada para educar. Puede distorsionar expectativas sobre el cuerpo, el deseo, el consentimiento y las relaciones. En este artículo hablamos de cómo mirarla con pensamiento crítico y qué recursos pueden ayudar a construir una sexualidad más sana, libre y respetuosa.",
                PublishedAt = new DateTime(2026, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                IsPublished = true,
                ImageUrl = ""
            },
            new()
            {
                Title = "Pense que el problema era mi cuerpo",
                Slug = "problema-era-mi-cuerpo",
                Category = "realidades",
                SubCategory = "presion-social",
                AuthorName = "Historia real",
                Content = "<p>Nunca nadie me dijo directamente que mi cuerpo estaba mal. Pero lo senti muchas veces. En los comentarios de otras personas, en las miradas, en las comparaciones constantes con lo que se supone que hay que ser.</p>",
                Excerpt = "Nunca nadie me dijo directamente que mi cuerpo estaba mal. Pero lo senti muchas veces.",
                PublishedAt = new DateTime(2026, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                IsPublished = true,
                ImageUrl = ""
            },
            new()
            {
                Title = "Metodos de barrera: el preservativo",
                Slug = "metodos-barrera-preservativo",
                Category = "cuidate",
                SubCategory = "metodos-barrera",
                AuthorName = "Sara Ibanez",
                Content = "<p>El preservativo masculino (condon) es el metodo mas eficaz para prevenir tanto ITS como embarazos no deseados cuando se usa correctamente. Tiene una eficacia del 98% con uso correcto. El preservativo femenino (femidom) ofrece alternativas y puede ser colocado hasta 8 horas antes de la relacion.</p>",
                Excerpt = "El preservativo sigue siendo el metodo mas eficaz para prevenir tanto ITS como embarazos no deseados.",
                PublishedAt = new DateTime(2026, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                IsPublished = true,
                ImageUrl = ""
            },
            new()
            {
                Title = "PrEP: que es y quien puede acceder",
                Slug = "prep-que-es",
                Category = "cuidate",
                SubCategory = "prep-pep",
                AuthorName = "Javier Ruiz",
                Content = "<p>La Profilaxis Pre-Exposicion (PrEP) es un medicamento que toman personas VIH negativas para prevenir la infeccion. Tiene una eficacia cercana al 99% cuando se toma correctamente. En Espana esta financiado por el Sistema Nacional de Salud para personas con alto riesgo de exposicion al VIH.</p>",
                Excerpt = "La profilaxis pre-exposicion al VIH tiene una eficacia cercana al 99% cuando se toma correctamente.",
                PublishedAt = new DateTime(2026, 5, 5, 0, 0, 0, DateTimeKind.Utc),
                IsPublished = true,
                ImageUrl = ""
            },
            new()
            {
                Title = "ChemSex: cuando las drogas y el sexo se mezclan",
                Slug = "chemsex-drogas-y-sexo",
                Category = "realidades",
                SubCategory = "chemsex",
                AuthorName = "Javier Ruiz",
                Content = """
                    <p>El ChemSex es la practica de consumir sustancias psicoactivas especificas con el objetivo de potenciar, prolongar o facilitar las relaciones sexuales. Las sustancias mas frecuentemente asociadas son la metanfetamina, la mefedrona y el GHB/GBL, aunque tambien puede implicar otras drogas como la ketamina o el poppers.</p>
                    <p>Aunque puede darse en cualquier persona, el ChemSex esta documentado principalmente en la comunidad de hombres que tienen sexo con hombres (HSH), donde factores como el estigma, la soledad o la busqueda de desinhibicion social pueden actuar como desencadenantes.</p>

                    <h2>¿Que riesgos tiene?</h2>
                    <p>El ChemSex no es solo un tema de salud sexual. Sus riesgos son multiples:</p>
                    <ul>
                      <li><strong>Riesgos para la salud sexual:</strong> bajo los efectos de estas sustancias aumenta la probabilidad de tener relaciones sin proteccion, lo que incrementa el riesgo de transmision de VIH y otras ITS. Ademas, las lesiones genitales pueden pasar desapercibidas por el efecto anestesiante de algunas drogas.</li>
                      <li><strong>Riesgos de salud mental:</strong> el uso continuado puede generar ansiedad, paranoia, depresion y episodios psicoticos, especialmente asociados a la metanfetamina.</li>
                      <li><strong>Riesgo de sobredosis:</strong> el GHB y el GBL tienen un margen de seguridad muy estrecho. Una dosis ligeramente superior a la habitual puede provocar perdida de consciencia, coma o muerte. Combinados con alcohol, el riesgo se multiplica.</li>
                      <li><strong>Dependencia:</strong> aunque no todas las personas que practican ChemSex desarrollan una adiccion, las sustancias implicadas tienen alto potencial adictivo.</li>
                    </ul>

                    <h2>¿Por que cuesta pedir ayuda?</h2>
                    <p>Muchas personas que practican ChemSex no buscan ayuda por miedo al juicio, a la discriminacion o a no ser comprendidas. El estigma que rodea tanto el consumo de drogas como la sexualidad de los colectivos mas afectados dificulta el acceso a recursos sanitarios.</p>
                    <p>Desde BE nurse queremos que sepas que aqui no hay juicios. Si tienes dudas, si crees que el consumo esta afectando tu vida o si simplemente quieres informarte, puedes escribirnos en el chat anonimo.</p>

                    <h2>¿Como reducir riesgos?</h2>
                    <p>Si en este momento no puedes o no quieres dejar de consumir, hay medidas que pueden reducir el riesgo:</p>
                    <ul>
                      <li>No mezclar GHB o GBL con alcohol ni otras depresoras del sistema nervioso central.</li>
                      <li>No consumir solo. Tener a alguien de confianza cerca puede salvar una vida en caso de sobredosis.</li>
                      <li>Hacerse pruebas de ITS con regularidad, especialmente VIH y hepatitis C.</li>
                      <li>Usar siempre metodos de barrera (preservativo, dental dam).</li>
                      <li>Informar a tu medico o enfermero sobre el consumo para recibir atencion sin juicios.</li>
                    </ul>
                    <blockquote>No estas solo o sola. Pedir ayuda es un acto de valentia.</blockquote>
                    """,
                Excerpt = "El ChemSex es el uso de sustancias como metanfetamina, mefedrona o GHB para potenciar relaciones sexuales. Entender sus riesgos es clave para tomar decisiones informadas y pedir ayuda sin miedo.",
                PublishedAt = new DateTime(2026, 4, 20, 0, 0, 0, DateTimeKind.Utc),
                IsPublished = true,
                ImageUrl = ""
            }
        };

        // El contenido editorial vive en este seed y no hay panel de edicion de articulos,
        // asi que los existentes se refrescan en cada arranque: sin esto, cambiar un texto
        // aqui no llegaria nunca a una base de datos ya poblada.
        var slugs = seed.Select(a => a.Slug).ToList();
        var existing = await context.Articles
            .Where(a => slugs.Contains(a.Slug))
            .ToDictionaryAsync(a => a.Slug);

        foreach (var article in seed)
        {
            if (existing.TryGetValue(article.Slug, out var current))
            {
                current.Title = article.Title;
                current.Category = article.Category;
                current.SubCategory = article.SubCategory;
                current.AuthorName = article.AuthorName;
                current.Content = article.Content;
                current.Excerpt = article.Excerpt;
                current.ImageUrl = article.ImageUrl;
                current.IsPublished = article.IsPublished;
            }
            else
            {
                context.Articles.Add(article);
            }
        }

        await context.SaveChangesAsync();
    }
}
